export const Data = [
  {
    id: 1,
    action: "no action allowed",
    teamName: "pro team gemink",
    competition: "ctf",
    institution: "Brawijaya",
    teamInfo: "Ali (Ketua)",
    submission: "Klick here",
  },
  {
    id: 2,
    action: "no action allowed",
    teamName: "duar meleduk",
    competition: "ctf",
    institution: "ITS",
    teamInfo: "Bambang (Ketua)",
    submission: "Klick here",
  },
  {
    id: 3,
    action: "no action allowed",
    teamName: "ngoding asik",
    competition: "cp",
    institution: "UI",
    teamInfo: "Kipli (Ketua)",
    submission: "Klick here",
  },
  {
    id: 4,
    action: "no action allowed",
    teamName: "satudua3",
    competition: "cp",
    institution: "Brawijaya",
    teamInfo: "Kipli (Ketua)",
    submission: "Klick here",
  },
  {
    id: 5,
    action: "no action allowed",
    teamName: "gambar bagus",
    competition: "uiux",
    institution: "Brawijaya",
    teamInfo: "tatang (Ketua)",
    submission: "Klick here",
  },
  {
    id: 6,
    action: "no action allowed",
    teamName: "newbeast",
    competition: "uiux",
    institution: "ITB",
    teamInfo: "Raihan (Ketua)",
    submission: "Klick here",
  },
  {
    id: 7,
    action: "no action allowed",
    userName: "Mohammad Ali Rafli",
    competition: "webinar",
    institution: "Brawijaya",
    webinar: ["webinar 1", "webinar 2", "webinar 3"],
  },
];
